'use client';
import { FormEvent, useMemo, useState } from 'react';
type Track={source:'bilibili'|'audio';url:string;id?:string;title:string};
const demo:Track={source:'bilibili',url:'https://www.bilibili.com/video/BV1GJ411x7h7',id:'BV1GJ411x7h7',title:'Bilibili 音乐'};
function parseTrack(input:string):Track|null{const value=input.trim();const bv=value.match(/BV[0-9A-Za-z]{10}/i)?.[0];if(bv)return{source:'bilibili',url:value,id:bv,title:`Bilibili · ${bv}`};if(/^https?:\/\/.+\.(mp3|m4a|aac|wav|ogg|flac)(\?.*)?$/i.test(value)){const name=decodeURIComponent(value.split('/').pop()?.split('?')[0]||'网络音频');return{source:'audio',url:value,title:name.replace(/\.[^.]+$/,'')}}return null}
export default function Home(){const[value,setValue]=useState('');const[track,setTrack]=useState<Track>(demo);const[error,setError]=useState('');const[compact,setCompact]=useState(false);const embed=useMemo(()=>track.id?`https://player.bilibili.com/player.html?bvid=${track.id}&page=1&high_quality=1&danmaku=0&autoplay=0`:'',[track.id]);function load(e:FormEvent){e.preventDefault();const next=parseTrack(value);if(!next){setError('暂时支持 Bilibili 视频链接（含 BV 号）和直接音频链接。');return}setTrack(next);setError('');setValue('')}
return <main className="app-shell"><header className="topbar"><a className="brand" href="#" aria-label="声笺首页"><span className="brand-mark"><i/><i/><i/></span><span>声笺</span></a><span className="status"><i/> 网页音频台</span></header>
<section className="hero"><p className="eyebrow">YOUR WEB, NOW PLAYING</p><h1>把网页里的声音，<br/><em>放进播放器。</em></h1><p className="intro">粘贴一个 Bilibili 视频或音频直链，关掉弹幕与干扰，留下此刻想听的声音。</p><form className="link-form" onSubmit={load}><span className="link-icon">↗</span><input aria-label="网页或音频链接" value={value} onChange={e=>setValue(e.target.value)} placeholder="粘贴 Bilibili 或音频链接…"/><button type="submit">载入 <span>→</span></button></form><div className="form-meta"><span>{error||'支持 bilibili.com/video/BV… · MP3 / M4A / OGG'}</span><button type="button" onClick={()=>setValue(demo.url)}>试试示例</button></div></section>
<section className={`player-card ${compact?'is-compact':''}`} aria-label="音乐播放器"><div className="artwork">{track.source==='bilibili'?<iframe key={embed} src={embed} title={`${track.title} 播放界面`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<div className="record-art"><span>♪</span><i/></div>}</div><div className="player-body"><div className="track-heading"><div><p className="source-label">{track.source==='bilibili'?'BILIBILI · 网页播放':'DIRECT AUDIO · 网络音频'}</p><h2>{track.title}</h2><p className="subline">{track.source==='bilibili'?'请在左侧画面中点击播放':'来自你粘贴的音频地址'}</p></div><button className="collapse" type="button" onClick={()=>setCompact(!compact)} aria-label="切换精简模式">{compact?'展开':'—'}</button></div>{track.source==='audio'?<audio className="native-audio" controls autoPlay src={track.url}>你的浏览器不支持音频播放。</audio>:<div className="bili-note"><span className="pulse">▶</span><p><strong>播放由 Bilibili 提供</strong><br/>保留原站播放控件，安全且不提取音频文件。</p></div>}<div className="player-footer"><span className="source-pill">{track.source==='bilibili'?'哔哩哔哩':'音频直链'}</span><a href={track.url} target="_blank" rel="noreferrer">查看原网页 ↗</a></div></div></section><footer><span>声笺 · MUSIC FROM THE WEB</span><p>不下载，不转码，不保存媒体文件</p></footer></main>}
